// SPDX-License-Identifier: UNLICENSED
// Unit tests for the C# emitter -- input is a parsed MermaidEntity, output is
// the generated `.g.cs` source string. Determinism (byte-identical re-emit)
// is a first-class concern: two runs over the same model must produce the
// same source.

using FluentAssertions;
using Oasis.SurrealDb.Schema.Mermaid;
using Oasis.SurrealDb.SourceGen;

namespace Oasis.SurrealDb.SourceGen.Tests;

public class CSharpEmitterTests
{
    private static MermaidEntity ParseFirstEntity(string mermaidSource)
    {
        var model = MermaidParser.Parse(mermaidSource, "test.mermaid");
        model.Entities.Should().HaveCountGreaterThan(0);
        return model.Entities[0];
    }

    [Fact]
    public void Emits_partial_class_with_namespace_and_using_block()
    {
        var src = """
            erDiagram
                wallet {
                    string id
                    string avatar_id
                }
            """;
        var entity = ParseFirstEntity(src);
        var emitter = new CSharpEmitter("MyApp.Generated");
        var output = emitter.Emit(entity);

        output.Should().Contain("// <auto-generated />");
        output.Should().Contain("namespace MyApp.Generated");
        output.Should().Contain("public partial class Wallet");
        output.Should().Contain(": global::Oasis.SurrealDb.Client.ISurrealRecord");
        output.Should().Contain("using System.Text.Json.Serialization;");
        output.Should().Contain("using Oasis.SurrealDb.Client;");
    }

    [Fact]
    public void Emits_SchemaName_constants_matching_table()
    {
        var src = """
            erDiagram
                idempotency_key_store {
                    string id
                }
            """;
        var entity = ParseFirstEntity(src);
        var emitter = new CSharpEmitter("X");
        var output = emitter.Emit(entity);

        output.Should().Contain("public const string SchemaNameConst = \"idempotency_key_store\";");
        output.Should().Contain("public string SchemaName => SchemaNameConst;");
    }

    [Fact]
    public void Emits_JsonPropertyName_with_snake_case_column()
    {
        var src = """
            erDiagram
                wallet {
                    string avatar_id
                }
            """;
        var entity = ParseFirstEntity(src);
        var emitter = new CSharpEmitter("X");
        var output = emitter.Emit(entity);

        output.Should().Contain("[JsonPropertyName(\"avatar_id\")]");
        output.Should().Contain("public string AvatarId { get; set; }");
    }

    [Fact]
    public void Maps_option_to_nullable_property()
    {
        var src = """
            erDiagram
                wallet {
                    option<string> label
                }
            """;
        var entity = ParseFirstEntity(src);
        var emitter = new CSharpEmitter("X");
        var output = emitter.Emit(entity);

        output.Should().Contain("public string? Label { get; set; }");
    }

    [Fact]
    public void Maps_datetime_to_DateTimeOffset()
    {
        var src = """
            erDiagram
                wallet {
                    datetime created_at
                }
            """;
        var entity = ParseFirstEntity(src);
        var emitter = new CSharpEmitter("X");
        var output = emitter.Emit(entity);

        output.Should().Contain("public global::System.DateTimeOffset CreatedAt { get; set; }");
    }

    [Fact]
    public void Generates_enum_for_string_ASSERT_INSIDE_field()
    {
        var src = """
            erDiagram
                wallet {
                    %% @surreal.assert "$value INSIDE [\"External\", \"Platform\"]"
                    string wallet_type
                }
            """;
        var entity = ParseFirstEntity(src);
        var emitter = new CSharpEmitter("X");
        var output = emitter.Emit(entity);

        // Enum name carries a `Kind` suffix so the nested enum does not
        // collide with the property of the same identifier.
        output.Should().Contain("public enum WalletTypeKind");
        output.Should().Contain("External");
        output.Should().Contain("Platform");
        output.Should().Contain("public Wallet.WalletTypeKind WalletType { get; set; }");
        output.Should().Contain("[JsonConverter(typeof(JsonStringEnumConverter))]");
    }

    [Fact]
    public void Generator_is_deterministic_two_runs_byte_identical()
    {
        var src = """
            erDiagram
                wallet {
                    string id
                    string avatar_id
                    option<string> label
                    %% @surreal.assert "$value INSIDE [\"External\", \"Platform\"]"
                    string wallet_type
                    datetime created_at
                }
            """;
        var entity = ParseFirstEntity(src);
        var emitter1 = new CSharpEmitter("MyApp.Generated");
        var emitter2 = new CSharpEmitter("MyApp.Generated");

        var output1 = emitter1.Emit(entity);
        var output2 = emitter2.Emit(entity);

        output2.Should().Be(output1);
    }

    [Fact]
    public void Annotation_csharp_property_overrides_default_translation()
    {
        var src = """
            erDiagram
                wallet {
                    %% @surreal.csharp.property name=AvatarUuid
                    string avatar_id
                }
            """;
        var entity = ParseFirstEntity(src);
        var emitter = new CSharpEmitter("X");
        var output = emitter.Emit(entity);

        output.Should().Contain("public string AvatarUuid { get; set; }");
        output.Should().NotContain("public string AvatarId { get; set; }");
    }

    [Fact]
    public void Annotation_csharp_skip_omits_field()
    {
        var src = """
            erDiagram
                wallet {
                    string id
                    %% @surreal.csharp.skip
                    string internal_only
                }
            """;
        var entity = ParseFirstEntity(src);
        var emitter = new CSharpEmitter("X");
        var output = emitter.Emit(entity);

        output.Should().Contain("public string Id { get; set; }");
        output.Should().NotContain("InternalOnly");
        output.Should().NotContain("internal_only");
    }

    [Fact]
    public void Unsupported_surreal_type_throws_NotSupportedException()
    {
        var src = """
            erDiagram
                wallet {
                    uuid id
                }
            """;
        var entity = ParseFirstEntity(src);
        var emitter = new CSharpEmitter("X");

        var act = () => emitter.Emit(entity);
        act.Should().Throw<NotSupportedException>()
           .WithMessage("*uuid*");
    }

    [Fact]
    public void Record_of_T_property_uses_RecordId_typed_generic()
    {
        var src = """
            erDiagram
                bridge_tx {
                    record<idempotency_key_store> idempotency_key_record
                }
            """;
        var entity = ParseFirstEntity(src);
        var emitter = new CSharpEmitter("X");
        var output = emitter.Emit(entity);

        output.Should().Contain("global::Oasis.SurrealDb.Client.RecordId<IdempotencyKeyStore>");
        output.Should().Contain("IdempotencyKeyRecord");
    }

    [Fact]
    public void Snake_case_table_name_becomes_PascalCase_class()
    {
        var src = """
            erDiagram
                idempotency_key_store {
                    string id
                }
            """;
        var entity = ParseFirstEntity(src);
        var emitter = new CSharpEmitter("X");
        var output = emitter.Emit(entity);

        output.Should().Contain("public partial class IdempotencyKeyStore");
    }

    [Fact]
    public void String_field_default_initializer_is_string_empty()
    {
        var src = """
            erDiagram
                wallet {
                    string id
                }
            """;
        var entity = ParseFirstEntity(src);
        var emitter = new CSharpEmitter("X");
        var output = emitter.Emit(entity);

        output.Should().Contain("public string Id { get; set; } = string.Empty;");
    }

    [Fact]
    public void Array_field_default_initializer_is_array_empty()
    {
        var src = """
            erDiagram
                wallet {
                    array<string> tags
                }
            """;
        var entity = ParseFirstEntity(src);
        var emitter = new CSharpEmitter("X");
        var output = emitter.Emit(entity);

        output.Should().Contain("public global::System.Collections.Generic.IReadOnlyList<string> Tags { get; set; }");
        output.Should().Contain("= global::System.Array.Empty<string>();");
    }
}
