// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OASIS.WebAPI.Data;

#nullable disable

namespace OASIS.WebAPI.Migrations
{
    [DbContext(typeof(OASISDbContext))]
    [Migration("20260511144859_AddApiKeys")]
    partial class AddApiKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OASIS.WebAPI.Models.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AvatarId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Scopes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("KeyPrefix");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.Avatar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<int>("Karma")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastBeamedInDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Title")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Avatars");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.AvatarNFT", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AvatarId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChainType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CurrentOwner")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("ImageURI")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSoulbound")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTransferable")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastTransferDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataURI")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("MintedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NFTContractAddress")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("RoyaltyPercentage")
                        .HasColumnType("numeric");

                    b.Property<string>("RoyaltyRecipient")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TokenStandard")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.HasIndex("ChainType");

                    b.HasIndex("CurrentOwner");

                    b.HasIndex("NFTContractAddress");

                    b.HasIndex("TokenId");

                    b.ToTable("AvatarNFTs");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.BlockchainOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<string>("AssetType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("AvatarId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExchangeRate")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecipientAddress")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("SourceHolonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("TargetHolonId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenUri")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid?>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.HasIndex("OperationType");

                    b.HasIndex("Status");

                    b.HasIndex("WalletId");

                    b.ToTable("BlockchainOperations");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.Holon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("AvatarId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChainId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ParentHolonId")
                        .HasColumnType("uuid");

                    b.Property<string>("PeerHolonIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TokenId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.HasIndex("ChainId");

                    b.HasIndex("Name");

                    b.HasIndex("ParentHolonId");

                    b.HasIndex("ProviderName");

                    b.ToTable("Holons");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.HolonNFTBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AvatarNFTId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HolonId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PermissionLevel")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarNFTId");

                    b.HasIndex("HolonId");

                    b.ToTable("HolonNFTBindings");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.Quest.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AvatarId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DappSeriesId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.HasIndex("DappSeriesId");

                    b.HasIndex("Status");

                    b.HasIndex("TemplateId");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.Quest.QuestDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DependencyType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DependsOnNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DependsOnQuestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnQuestId");

                    b.HasIndex("QuestId");

                    b.ToTable("QuestDependencies");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.Quest.QuestEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .HasColumnType("text");

                    b.Property<int>("EdgeType")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestId");

                    b.HasIndex("SourceNodeId", "TargetNodeId")
                        .IsUnique();

                    b.ToTable("QuestEdges");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.Quest.QuestNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("ExecutionOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEntry")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("NodeTemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("NodeType")
                        .HasColumnType("integer");

                    b.Property<string>("Output")
                        .HasColumnType("text");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NodeType");

                    b.HasIndex("QuestId");

                    b.HasIndex("State");

                    b.ToTable("QuestNodes");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.Quest.QuestNodeTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorAvatarId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigSchema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultConfig")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("InputSchema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NodeType")
                        .HasColumnType("integer");

                    b.Property<string>("OutputSchema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsPublic");

                    b.HasIndex("NodeType");

                    b.ToTable("QuestNodeTemplates");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.Quest.QuestTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorAvatarId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorAvatarId");

                    b.HasIndex("IsPublic");

                    b.ToTable("QuestTemplates");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.Quest.QuestTemplateEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EdgeType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("QuestTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceSlotId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TargetSlotId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestTemplateId");

                    b.HasIndex("TemplateId");

                    b.ToTable("QuestTemplateEdges");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.Quest.QuestTemplateNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEntry")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NodeTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParamOverrides")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("QuestTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("SlotId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NodeTemplateId");

                    b.HasIndex("QuestTemplateId");

                    b.HasIndex("SlotId");

                    b.HasIndex("TemplateId");

                    b.ToTable("QuestTemplateNodes");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.STARODK", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AvatarId")
                        .HasColumnType("uuid");

                    b.Property<string>("BoundHolonIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeploymentConfig")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("GeneratedCode")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PrivateKeyHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PublicKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("TargetChain")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.HasIndex("Name");

                    b.ToTable("STARODKs");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("AvatarId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChainType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PublicKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Address");

                    b.HasIndex("AvatarId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.WalletNFTBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessLevel")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AccessPermissions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AvatarNFTId")
                        .HasColumnType("uuid");

                    b.Property<string>("BindingType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AvatarNFTId");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletNFTBindings");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.ApiKey", b =>
                {
                    b.HasOne("OASIS.WebAPI.Models.Avatar", null)
                        .WithMany()
                        .HasForeignKey("AvatarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.AvatarNFT", b =>
                {
                    b.HasOne("OASIS.WebAPI.Models.Avatar", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.Holon", b =>
                {
                    b.HasOne("OASIS.WebAPI.Models.Holon", "ParentHolon")
                        .WithMany("SubHolons")
                        .HasForeignKey("ParentHolonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentHolon");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.HolonNFTBinding", b =>
                {
                    b.HasOne("OASIS.WebAPI.Models.AvatarNFT", "AvatarNFT")
                        .WithMany("HolonBindings")
                        .HasForeignKey("AvatarNFTId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OASIS.WebAPI.Models.Holon", "Holon")
                        .WithMany()
                        .HasForeignKey("HolonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvatarNFT");

                    b.Navigation("Holon");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.Quest.QuestDependency", b =>
                {
                    b.HasOne("OASIS.WebAPI.Models.Quest.Quest", null)
                        .WithMany("Dependencies")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.Quest.QuestEdge", b =>
                {
                    b.HasOne("OASIS.WebAPI.Models.Quest.Quest", null)
                        .WithMany("Edges")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.Quest.QuestNode", b =>
                {
                    b.HasOne("OASIS.WebAPI.Models.Quest.Quest", null)
                        .WithMany("Nodes")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.Quest.QuestTemplateEdge", b =>
                {
                    b.HasOne("OASIS.WebAPI.Models.Quest.QuestTemplate", null)
                        .WithMany("Edges")
                        .HasForeignKey("QuestTemplateId");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.Quest.QuestTemplateNode", b =>
                {
                    b.HasOne("OASIS.WebAPI.Models.Quest.QuestTemplate", null)
                        .WithMany("Nodes")
                        .HasForeignKey("QuestTemplateId");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.STARODK", b =>
                {
                    b.HasOne("OASIS.WebAPI.Models.Avatar", null)
                        .WithMany()
                        .HasForeignKey("AvatarId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.Wallet", b =>
                {
                    b.HasOne("OASIS.WebAPI.Models.Avatar", null)
                        .WithMany("Wallets")
                        .HasForeignKey("AvatarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.WalletNFTBinding", b =>
                {
                    b.HasOne("OASIS.WebAPI.Models.AvatarNFT", "AvatarNFT")
                        .WithMany("WalletBindings")
                        .HasForeignKey("AvatarNFTId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OASIS.WebAPI.Models.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvatarNFT");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.Avatar", b =>
                {
                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.AvatarNFT", b =>
                {
                    b.Navigation("HolonBindings");

                    b.Navigation("WalletBindings");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.Holon", b =>
                {
                    b.Navigation("SubHolons");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.Quest.Quest", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Edges");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("OASIS.WebAPI.Models.Quest.QuestTemplate", b =>
                {
                    b.Navigation("Edges");

                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
