// SPDX-License-Identifier: UNLICENSED
// Oasis.SurrealDb.SourceGen -- C# source emission for a single Mermaid entity.
//
// Given a MermaidEntity, produce a single .g.cs file with:
//   - // <auto-generated /> header
//   - namespace + using imports
//   - partial class implementing ISurrealRecord
//   - one property per attribute (with [JsonPropertyName])
//   - static SchemaName property naming the SurrealDB table
//   - sibling enum declarations for string ASSERT INSIDE [...] fields
//
// Determinism: fields are emitted in source order; enums likewise. Two runs
// over the same input produce byte-identical output.

#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Oasis.SurrealDb.Schema.Mermaid;

namespace Oasis.SurrealDb.SourceGen
{
    /// <summary>
    /// Produces the generated <c>.g.cs</c> source for a single
    /// <see cref="MermaidEntity"/>. Stateless across entities; one instance
    /// is reused only within a single entity emit so namespace state is
    /// consistent.
    /// </summary>
    public sealed class CSharpEmitter
    {
        private const string IndentUnit = "    ";

        private readonly string _namespace;

        public CSharpEmitter(string ns)
        {
            if (string.IsNullOrWhiteSpace(ns))
                throw new ArgumentException("Namespace must not be empty.", nameof(ns));
            _namespace = ns;
        }

        /// <summary>
        /// Emit the source for one entity. Throws <see cref="NotSupportedException"/>
        /// when a field's SurrealDB type cannot be mapped.
        /// </summary>
        public string Emit(MermaidEntity entity)
        {
            if (entity == null) throw new ArgumentNullException(nameof(entity));

            var className = CSharpTypeMapper.ToPascalCase(entity.Name);
            var sb = new StringBuilder(1024);

            // File header.
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// Generated by Oasis.SurrealDb.SourceGen from " + EscapeFilePath(entity) + ".");
            sb.AppendLine("// DO NOT EDIT -- changes will be overwritten on the next build.");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Text.Json.Serialization;");
            sb.AppendLine("using Oasis.SurrealDb.Client;");
            sb.AppendLine();
            sb.AppendLine("namespace " + _namespace);
            sb.AppendLine("{");

            // Collect ASSERT INSIDE enums (referenced by properties below).
            // They are emitted as NESTED enums inside the partial class so the
            // `<ClassName>.<EnumName>` references in property declarations
            // resolve without extra namespace traversal.
            var enums = CollectAssertInsideEnums(entity, className);

            // Class.
            sb.AppendLine(IndentUnit + "/// <summary>");
            sb.AppendLine(IndentUnit + "/// Generated SurrealDB POCO for table <c>" + entity.Name + "</c>.");
            sb.AppendLine(IndentUnit + "/// Schema source: " + EscapeFilePath(entity));
            sb.AppendLine(IndentUnit + "/// </summary>");
            sb.AppendLine(IndentUnit + "public partial class " + className + " : global::Oasis.SurrealDb.Client.ISurrealRecord");
            sb.AppendLine(IndentUnit + "{");

            // Nested enums first, so property declarations below can refer to
            // them via the unqualified short name within the class body.
            foreach (var en in enums)
            {
                EmitEnum(sb, en);
            }

            // SchemaName: static for type-level lookup; instance shim for the
            // ISurrealRecord interface contract (netstandard2.0 has no
            // static-abstract-on-interface support).
            sb.AppendLine(IndentUnit + IndentUnit + "/// <summary>The SurrealDB table name this POCO maps to.</summary>");
            sb.AppendLine(IndentUnit + IndentUnit + "public const string SchemaNameConst = \"" + entity.Name + "\";");
            sb.AppendLine();
            sb.AppendLine(IndentUnit + IndentUnit + "/// <inheritdoc />");
            sb.AppendLine(IndentUnit + IndentUnit + "public string SchemaName => SchemaNameConst;");
            sb.AppendLine();

            // Properties: one per attribute, in source order.
            bool firstProperty = true;
            foreach (var attr in entity.Attributes)
            {
                if (HasSkipDirective(attr)) continue;

                if (!firstProperty) sb.AppendLine();
                firstProperty = false;

                EmitProperty(sb, attr, className, enums);
            }

            sb.AppendLine(IndentUnit + "}");
            sb.AppendLine("}");

            return sb.ToString();
        }

        // ─── Property emission ───────────────────────────────────────────────

        private static void EmitProperty(
            StringBuilder sb,
            MermaidAttribute attr,
            string parentClassName,
            IReadOnlyList<AssertInsideEnum> enums)
        {
            // C# property name: PascalCase, override via @surreal.csharp.property name=...
            string propName = GetCsharpPropertyOverride(attr) ?? CSharpTypeMapper.ToPascalCase(attr.Name);

            // Pick the enum sibling for string ASSERT INSIDE [...] if present.
            var enumForField = enums.FirstOrDefault(e => string.Equals(e.SourceFieldName, attr.Name, StringComparison.Ordinal));
            string propType;
            if (enumForField != null)
            {
                var nullable = attr.Type.StartsWith("option<", StringComparison.Ordinal);
                propType = parentClassName + "." + enumForField.EnumName + (nullable ? "?" : "");
            }
            else
            {
                var typeRef = CSharpTypeMapper.Map(attr.Type);
                propType = typeRef.ToPropertyType();
            }

            // Doc comment from Mermaid trailing comment, if any.
            if (!string.IsNullOrEmpty(attr.Comment))
            {
                sb.AppendLine(IndentUnit + IndentUnit + "/// <summary>" + EscapeXml(attr.Comment!) + "</summary>");
            }

            // [JsonPropertyName("snake_case")]
            sb.AppendLine(IndentUnit + IndentUnit + "[JsonPropertyName(\"" + attr.Name + "\")]");
            if (enumForField != null)
            {
                sb.AppendLine(IndentUnit + IndentUnit + "[JsonConverter(typeof(JsonStringEnumConverter))]");
            }

            // Default initializer for non-nullable reference-typed properties so
            // the generated class is friendly to deserialization with missing
            // fields. Mirrors hand-written models which used `= string.Empty`.
            string initializer = SuggestInitializer(propType);
            string trailer = initializer.Length > 0 ? " = " + initializer + ";" : "";

            sb.AppendLine(IndentUnit + IndentUnit + "public " + propType + " " + propName + " { get; set; }" + trailer);
        }

        private static string SuggestInitializer(string propType)
        {
            // Only initialize non-nullable string and IReadOnlyList<T> properties.
            // Other value types and nullable references default to default(T)/null.
            if (propType == "string") return "string.Empty";
            if (propType.StartsWith("global::System.Collections.Generic.IReadOnlyList<", StringComparison.Ordinal)
                && !propType.EndsWith("?", StringComparison.Ordinal))
            {
                // Extract inner.
                int open = propType.IndexOf('<');
                int close = propType.LastIndexOf('>');
                if (open > 0 && close > open)
                {
                    var inner = propType.Substring(open + 1, close - open - 1);
                    return "global::System.Array.Empty<" + inner + ">()";
                }
            }
            return string.Empty;
        }

        // ─── Enum emission ───────────────────────────────────────────────────

        private static void EmitEnum(StringBuilder sb, AssertInsideEnum en)
        {
            // Nested enums inside the partial class -- emit at one indent level
            // deeper than the class body itself.
            sb.AppendLine(IndentUnit + IndentUnit + "/// <summary>");
            sb.AppendLine(IndentUnit + IndentUnit + "/// Enum derived from <c>ASSERT INSIDE [...]</c> on field <c>" + en.SourceFieldName + "</c>.");
            sb.AppendLine(IndentUnit + IndentUnit + "/// </summary>");
            sb.AppendLine(IndentUnit + IndentUnit + "public enum " + en.EnumName);
            sb.AppendLine(IndentUnit + IndentUnit + "{");
            for (int i = 0; i < en.Members.Count; i++)
            {
                var member = en.Members[i];
                var sep = i < en.Members.Count - 1 ? "," : "";
                // Preserve the SurrealDB literal verbatim via JsonStringEnumConverter:
                // the C# identifier is sanitized; mapping to the underlying string
                // happens at JSON ser/deser. The string values match enum identifier
                // by convention; for verbatim mapping consumers can adjust.
                sb.AppendLine(IndentUnit + IndentUnit + IndentUnit + member + sep);
            }
            sb.AppendLine(IndentUnit + IndentUnit + "}");
            sb.AppendLine();
        }

        // ─── Annotation lookups ──────────────────────────────────────────────

        private static bool HasSkipDirective(MermaidAttribute attr)
        {
            foreach (var ann in attr.Annotations)
            {
                if (ann.Directive == "csharp" && ann.Arguments.ContainsKey("skip"))
                {
                    return true;
                }
            }
            return false;
        }

        private static string? GetCsharpPropertyOverride(MermaidAttribute attr)
        {
            foreach (var ann in attr.Annotations)
            {
                if (ann.Directive == "csharp" && ann.Arguments.TryGetValue("name", out var name))
                {
                    if (!string.IsNullOrWhiteSpace(name)) return name;
                }
            }
            return null;
        }

        // ─── Enum collection ─────────────────────────────────────────────────

        private static IReadOnlyList<AssertInsideEnum> CollectAssertInsideEnums(MermaidEntity entity, string parentClassName)
        {
            var result = new List<AssertInsideEnum>();
            foreach (var attr in entity.Attributes)
            {
                if (HasSkipDirective(attr)) continue;
                // Only on string / option<string> fields.
                bool isString = attr.Type == "string" || attr.Type == "option<string>";
                if (!isString) continue;

                foreach (var ann in attr.Annotations)
                {
                    if (ann.Directive != "assert") continue;
                    var values = ExtractInsideValues(ann.RawArguments);
                    if (values == null || values.Count == 0) continue;

                    // Enum name = PascalCase(field) with a `Kind` suffix to
                    // avoid the C# "type 'X' already contains a definition
                    // for 'X'" diagnostic when the property and its (nested)
                    // enum type would otherwise share the same identifier
                    // (e.g. property `WalletType` of nested enum `WalletType`).
                    var propertyName = CSharpTypeMapper.ToPascalCase(attr.Name);
                    var enumName = propertyName + "Kind";
                    var members = values.Select(SanitizeEnumMember).Distinct(StringComparer.Ordinal).ToList();
                    result.Add(new AssertInsideEnum(attr.Name, enumName, members));
                    break;
                }
            }
            return result;
        }

        /// <summary>
        /// Extract the bracketed list from a SurrealQL <c>ASSERT</c> expression
        /// of the form <c>"$value INSIDE [\"A\", \"B\"]"</c>. Returns null if
        /// the expression is not an <c>INSIDE</c> assertion.
        /// </summary>
        internal static IReadOnlyList<string>? ExtractInsideValues(string raw)
        {
            if (string.IsNullOrEmpty(raw)) return null;
            // The annotation value is a single double-quoted string that the
            // Mermaid parser strips the outer quotes from. Detect "INSIDE [..."
            int insideIdx = raw.IndexOf("INSIDE", StringComparison.Ordinal);
            if (insideIdx < 0) return null;
            int lb = raw.IndexOf('[', insideIdx);
            if (lb < 0) return null;
            int rb = raw.LastIndexOf(']');
            if (rb <= lb) return null;
            var body = raw.Substring(lb + 1, rb - lb - 1);

            // Split on commas, trim, strip surrounding escaped quotes if present.
            var result = new List<string>();
            foreach (var raw2 in body.Split(','))
            {
                var s = raw2.Trim();
                if (s.Length >= 2 && s[0] == '"' && s[s.Length - 1] == '"')
                {
                    s = s.Substring(1, s.Length - 2);
                }
                // Unescape backslash-quote.
                s = s.Replace("\\\"", "\"");
                if (s.Length > 0) result.Add(s);
            }
            return result;
        }

        private static string SanitizeEnumMember(string literal)
        {
            // First strip any leading / trailing escape-quote sequences that
            // survived the Mermaid annotation parse (e.g. `\"External\"` becomes
            // `External`). Then replace any remaining non-identifier char with
            // underscore. Identifiers may not start with a digit -- prepend `_`
            // in that case.
            var trimmed = literal;
            // Strip surrounding \"...\" (backslash-quote pairs).
            if (trimmed.Length >= 4 && trimmed.StartsWith("\\\"", StringComparison.Ordinal) && trimmed.EndsWith("\\\"", StringComparison.Ordinal))
            {
                trimmed = trimmed.Substring(2, trimmed.Length - 4);
            }
            // Strip surrounding "..." too in case the parser already unescaped.
            else if (trimmed.Length >= 2 && trimmed[0] == '"' && trimmed[trimmed.Length - 1] == '"')
            {
                trimmed = trimmed.Substring(1, trimmed.Length - 2);
            }
            var sb = new StringBuilder(trimmed.Length);
            for (int i = 0; i < trimmed.Length; i++)
            {
                char c = trimmed[i];
                if (char.IsLetterOrDigit(c) || c == '_')
                {
                    sb.Append(c);
                }
                else
                {
                    sb.Append('_');
                }
            }
            if (sb.Length == 0) return "_";
            // Identifiers may not start with a digit.
            if (char.IsDigit(sb[0])) sb.Insert(0, '_');
            return sb.ToString();
        }

        // ─── Helpers ─────────────────────────────────────────────────────────

        private static string EscapeFilePath(MermaidEntity entity)
        {
            // Use a stable, OS-neutral representation: take last path segment only
            // so generated source is identical across OSes / CI machines.
            // (Determinism guard.)
            var src = entity.Name; // Best stable token we have without re-threading file context.
            return src + " (entity)";
        }

        private static string EscapeXml(string text)
        {
            return text
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;");
        }

        /// <summary>
        /// One detected <c>string ASSERT INSIDE [...]</c> closed-set field +
        /// its derived C# enum name and member set.
        /// </summary>
        internal sealed class AssertInsideEnum
        {
            public string SourceFieldName { get; }
            public string EnumName { get; }
            public IReadOnlyList<string> Members { get; }

            public AssertInsideEnum(string sourceFieldName, string enumName, IReadOnlyList<string> members)
            {
                SourceFieldName = sourceFieldName;
                EnumName = enumName;
                Members = members;
            }
        }
    }
}
